# orderbook column names
TIMESTAMP = 'timestamp'
GATEWAY_TIMESTAMP = 'gateway_timestamp'
SYM = 'sym'
MARKET = 'market'
BID_SIZES = 'bid_sizes'
BID_PRICES = 'bid_prices'
ASK_SIZES = 'ask_sizes'
ASK_PRICES = 'ask_prices'
MISC = 'misc'

BID = 'bid'
BIDS = 'bids'
ASK = 'ask'
ASKS = 'asks'
PRICE = 'price'
SIZE = 'size'